NDefines.NGame.END_DATE = "1970.1.1.1"
--NDefines.NAI.RESEARCH_WITH_XP_AI_WEIGHT_MULT = 1.8
--NDefines.NAI.CAPITAL_TASKFORCE_MAX_CAPITAL_COUNT = 6
--NDefines.NAI.SCREEN_TASKFORCE_MAX_SHIP_COUNT = 4
--NDefines.NAI.SUB_TASKFORCE_MAX_SHIP_COUNT = 6
--NDefines.NAI.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 4
--NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 2.0
