NDefines.NResistance.RESISTANCE_TARGET_BASE = 35.0
NDefines.NResistance.RESISTANCE_GROWTH_BASE = 0.230
NDefines.NResistance.COMPLIANCE_GROWTH_BASE = 0.115
NDefines.NResistance.COMPLIANCE_GROWTH_IS_AT_PEACE = 15
NDefines.NResistance.COMPLIANCE_DECAY_AT_MAX_COMPLIANCE = -0.075
NDefines.NCountry.MIN_STABILITY = -1.0