name: CWTools CI

on: [pull_request] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # required
      - uses: cwtools/cwtools-action@v1.0.0
        with:
          game: hoi4
          rules: "https://github.com/GEACPS-development-team/cwtools-hoi4-config.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, secret is automatically set by github
